# Generated by Django 4.0 on 2024-02-09 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_judge_event_feedback_totalresult_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='totalresult',
            name='id',
        ),
        migrations.AlterField(
            model_name='totalresult',
            name='team',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='total_result', serialize=False, to='app.team'),
        ),
    ]
