# Generated by Django 4.0 on 2024-02-09 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_totalresult_id_alter_totalresult_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='event',
        ),
    ]
