# Generated by Django 4.0 on 2024-02-09 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_profile_is_occupied'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registeration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivation_letter', models.TextField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registeration', to='app.event')),
                ('occupation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registeration', to='app.occupation')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registeration', to='app.profile')),
            ],
        ),
    ]
