# Generated by Django 4.0 on 2024-02-09 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_registeration'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipantRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivation_letter', models.TextField()),
                ('occupation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registration', to='app.occupation')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registration', to='app.profile')),
            ],
        ),
        migrations.CreateModel(
            name='TeamRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('number_of_team', models.PositiveSmallIntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='team_registration', to='app.event')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='judge',
            unique_together={('profile', 'event')},
        ),
        migrations.DeleteModel(
            name='Registeration',
        ),
        migrations.AddField(
            model_name='participantregistration',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registration', to='app.teamregistration'),
        ),
    ]
