# Generated by Django 4.0 on 2024-02-09 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_participantregistration_teamregistration_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teamregistration',
            unique_together={('event', 'name')},
        ),
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('activity', models.CharField(max_length=20)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agenda', to='app.event')),
            ],
            options={
                'unique_together': {('event', 'date_time')},
            },
        ),
    ]
