# Generated by Django 4.0 on 2024-02-10 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_teamregistration_unique_together_agenda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='password',
        ),
    ]
