# Generated by Django 4.0 on 2024-02-10 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_admin_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestMentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested', models.DateTimeField(auto_now_add=True)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='request_mentor', to='app.mentor')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='request_mentor', to='app.team')),
            ],
        ),
    ]
