# Generated by Django 4.0 on 2024-02-10 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_requestmentor'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteSession',
            fields=[
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='website_session', serialize=False, to='app.event')),
                ('grant_to_judge', models.BooleanField(default=False)),
                ('grant_to_participants', models.BooleanField(default=False)),
            ],
        ),
    ]
