# Generated by Django 4.0 on 2024-02-10 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_websitesession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='judge_password',
        ),
    ]
